######################################################################
# Automatically generated by qmake (3.0) ? 6? 9 15:29:37 2014
######################################################################

QT	+= core gui

TEMPLATE = app
TARGET = WEATHER-BOARD
INCLUDEPATH += .

# Input
HEADERS += ui_weather_board.h weather_board.h
FORMS += weather_board.ui
SOURCES += main.cpp weather_board.cpp

CONFIG += qwt
